version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/dist:/var/www/html
      - ./proxy/cert:/etc/letsencrypt/live/example.com/
    networks:
      - app-networks
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge