version: '3.8'

services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt/live/example.com/
    depends_on:
      - backend

  backend:
    build:
      context: ./code
      dockerfile: Dockerfile
    image: matvsuzu/plan-backend:latest
    command: python main.py
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
